language: node_js
node_js:
  - 10
services:
  - docker
env:
  global:
    - PACT_BROKER_BASE_URL=https://pinarlabs.pactflow.io
    - PACT_BROKER_PUBLISH_VERIFICATION_RESULTS=true
    # Encrypted PACT_BROKER_TOKEN
    - secure: "fPph59ghtYgAocRfXI4E6V8Id0AMO/vv/+83xpkmsCEJUmQy2trgLRY1dIXA2W02n4oV/YMu3DiaByTBkZm534pn1sdSWEKvo+mMeRtSo4RjNlAOIuDrJgNHSFD1pQHryi4TszIlFsGz9O9mGdrJ7Y63dNK0HKrD9U8VeMMDAoGP8xt0MyyiPzqtl223bWumhXzKnAWZTyMNtMmu+1TSrafaqfcq98m+BZfOr9I1TrMlsCEeI29DML8JJJZ4zZg3OSMpQwxSnjsFuy7jcxl7hOYzOkbk3+7O5c9ZLL3M1lHS/ZgV4YdQPRe8W1pEmITS+0m9aLqIsybMeSzNCNE01Hs34OetUkGHUK2mzsJhC3bUTOu3W4e1IN/milUzsEt9HiU4LocRhxg5FV/LzbNuMEx+gRMeJUJAkfS7o68RLyJFo/AlTkig9IV99me+XcTQf1/N0rYfxRQAc+7Km706W+a7xGhCEtxMeS2+i6nG2HF5HKN4gH++VtGU528Rnr71hG4QaeSCe5nkHv2W78SNwMLSl6t/Pv+7orIhqlA6Aew7nH40JhwPLiS4zTVdta2DJDZ/wwPbJKM/28d+1LpmtfAOFAK5PKcIMkYSqBKHOHGCn2n5AZ/6SS8HgQaE3Uc4iCiuwn2nr8f6+Vo4V/ilWNdW5DQd+ADS0BCtYCJBFH8="
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
  # When a webhook triggers a build, the PACT_URL will be set. In this case, just run the verification step.
  # Otherwise, run the normal build.
  # This is just to get around the fact that Travis CI only has one build definition per repository.
  # Normally you would define a separate job for the webhook triggered verification.
  - >
    if [ -n "${PACT_URL}" ]; then
      make ci_webhook
    else
      make ci
    fi
